# Generated by Django 4.2.3 on 2023-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('favorite_genre', models.CharField(max_length=70)),
                ('favorite_game', models.CharField(max_length=70)),
                ('quantity_of_hours', models.IntegerField()),
                ('hours_per_day', models.IntegerField()),
                ('first_experience', models.DateField()),
                ('favorite_male_character', models.CharField(max_length=70)),
                ('favorite_female_character', models.CharField(max_length=70)),
                ('device', models.CharField(max_length=70)),
            ],
        ),
    ]
